### ISSUE TITLE
紹介クーポンとポイント

### ISSUE THREAD

**Issue by daitosaito** [mogushare/mogushare#3]
# what
・もぐシェア内で割引に使えるポイント(もぐポイント)
・もぐポイント発行のための紹介クーポン

# why
ユーザーがもぐシェアのサービスをシェア拡散してくれるインセンティブを作りたい

# how
### ◎獲得条件と効果
・紹介クーポンはユーザー登録と同時に無条件で全ユーザーに付与(mogu-1ka4e2、のように)
・被紹介者が決済の際に他人の紹介クーポンを記入し購入した場合、500円分の割引になる
・紹介者は自分の紹介クーポンで決済された場合、もぐポイントが500円分蓄積
・紹介クーポンを記入して500円以下の購入を行う場合、差額はもぐポイントとして残る

### ◎仕様条件
・1ユーザーにつき発行される紹介クーポンは1つのみ
・自分の紹介クーポンはプロフィールページで確認可能
・自分で自分のクーポンを使うことはできない
・紹介クーポンを使っての決済は一度だけ可能
・ポイントは決済時に自ら使用したいポイント数を記載し使える
・紹介者に発行されたポイントの累計はユーザー毎にわかるようにしておく(viewとしては不要。一番ポイントを溜めた＝紹介してくれたユーザーに対してベストアンバサダー賞的な行いたいので運営がSQL叩いて出せればOK)

**Comment by nishisuke** [comment]
おっけ！

**Comment by nishisuke** [comment]
user_invitation_codes
  user_id
  code

user_points
  user_id
  point

user_point_logs
  user_id
  type
  amount
  detail

**Comment by nishisuke** [comment]
@daitosaito 確認！

すん(user) が
ひとつの招待コード: mogshare-hogehoge1234
をもってる。
それは不変。

以下連続的に動作を行う。

Nishisuke(被紹介者)がすんの招待コード(mogshare-hogehoge1234)
を購入時に入力すると500円引き

Nishisukeがもう一度すんの招待コード(mogshare-hogehoge1234)
を入力して買っても500円びきされない

その後Nishisukeがだいとの招待コード(mogshare-daidai9876)
を入力して買っても500円引きされない

**Comment by nishisuke** [comment]
これで認識あってる？

**Comment by nishisuke** [comment]
今編集した！

**Comment by nishisuke** [comment]
- 現状のユーザーに招待コード付与
- 登録時に招待コード付与
- 購入時のクーポンしよう処理 
  - check
  - 割引
  - 差額がある場合の処理
  - 割引けっか残す
  - ポイント付与
  - ポイント付与のログ
- ポイントの使用
  - 減額
  - ポイント減らす
  - ポイント減ったログ残す

コードリーディング
その他もろもろの表示など

**Comment by daitosaito** [comment]
@nishisuke 
認識相違ない！ちな現時点ではユーザー登録はされてないので(今はIPでデプロイしただけ)、その作業は不要かと！
